In [14]:
import numpy as np
import pandas as pd

In [58]:
#extract file into a frame
dframe = pd.read_csv('example.csv')

In [66]:
#testing code
pd.DataFrame(np.diag(dframe), index=[dframe.index, dframe.columns])

0
0 a   0
1 b   5
2 c  10
3 d  15

In [78]:
#establish arrays for each diagonal
indexneg3= np.diagonal(dframe,-3)
indexneg2= np.diagonal(dframe,-2)
indexneg1= np.diagonal(dframe,-1)
index0=np.diagonal(dframe)
index1=np.diagonal(dframe,1)
index2=np.diagonal(dframe,2)
index3=np.diagonal(dframe,3)



In [97]:
#visually inspecting each array
print(indexneg3)
print(indexneg2)
print(indexneg1)
print(index0)
print(index1)
print(index2)
print(index3)

[12]
[ 8 13]
[ 4  9 14]
[ 0  5 10 15]
[ 1  6 11]
[2 7]
[3]


In [191]:
#creating an array of arrays, labelling them, and putting them in a series
test = [indexneg3,indexneg2,indexneg1,index0,index1,index2,index3]
labels = [1,2,3,4,5,6,7]
diagonal_column = pd.Series(data = test, index = labels)


In [192]:
frame = pd.DataFrame(test, columns = ['A','B','C','D'],index = ['diag 1', 'diag 2', 'diag 3', 'diag 4', 'diag 5', 'diag 6', 'diag7'])

In [194]:
#visually inspecting 
frame 


A     B     C     D
diag 1  12   NaN   NaN   NaN
diag 2   8  13.0   NaN   NaN
diag 3   4   9.0  14.0   NaN
diag 4   0   5.0  10.0  15.0
diag 5   1   6.0  11.0   NaN
diag 6   2   7.0   NaN   NaN
diag7    3   NaN   NaN   NaN

In [188]:
#new column of means
frame['Mean'] = frame.mean(axis = 1)

In [189]:
#new column of standard deviations
frame['St Dev'] = frame.std(axis = 1)

In [190]:
#one final visual inspection
frame


A     B     C     D  Mean    St Dev
diag 1  12   NaN   NaN   NaN  12.0  0.000000
diag 2   8  13.0   NaN   NaN  10.5  2.500000
diag 3   4   9.0  14.0   NaN   9.0  4.082483
diag 4   0   5.0  10.0  15.0   7.5  5.590170
diag 5   1   6.0  11.0   NaN   6.0  4.082483
diag 6   2   7.0   NaN   NaN   4.5  2.500000
diag7    3   NaN   NaN   NaN   3.0  0.000000